name: analyse-phpStan-on-push
run-name: ${{ github.actor }} is running phpStan analyse on push
env :
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
on:
  push:
    branches:
      - master  # Adjust the branch name if needed
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - uses: php-actions/composer@v6
      - name: test  phpstan
        run: vendor/bin/phpstan analyse -c vendor/phpstan/phpstan/conf/phpstan.neon
  build:
    needs: tests
    runs-on: ubuntu-latest
    #on push le dockerfile sur dockerhub
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}:latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy project"