name: analyse-phpStan-on-push
run-name: ${{ github.actor }} is running phpStan analyse on push
on:
  push:
    branches:
      - master  # Adjust the branch name if needed
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - uses: php-actions/composer@v6
      - name: test  phpstan
        run: vendor/bin/phpstan analyse -c vendor/phpstan/phpstan/conf/phpstan.neon
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build app image"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy project"