name: analyse-phpStan-on-push
run-name: ${{ github.actor }} is running phpStan analyse on push
on: [push]
jobs:
  phpStan-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: vendor/bin/phpstan analyse -c vendor/phpstan/phpstan/conf/phpstan.neon
        continue-on-error: false
      - name: build
        run: echo "Build App Image"
      - name : deploy
        run: echo "Deploy App Image"