name: analyse-phpStan-on-push
run-name: ${{ github.actor }} is running phpStan analyse on push
env :
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
on:
  push:
    branches:
      - master  # Adjust the branch name if needed
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - uses: php-actions/composer@v6
      - name: test  phpstan
        run: vendor/bin/phpstan analyse -c vendor/phpstan/phpstan/conf/phpstan.neon
  build:
    needs: tests
    runs-on: ubuntu-latest
    #on push le dockerfile sur dockerhub
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: krowv/simple-app

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH
        uses: appleboy/ssh-action@master
        with:
          host: 162.19.74.216
          username: thomas
          key: ${{ secrets.SECRET_SSH }}
          port: 22
          script: |
            docker pull krowv/simple-app:latest