name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  phpStanAnalyse:
    name: PHPStan analyse
    runs-on: ubuntu-latest
    steps:
      - name: PHPStan analyse
        run: composer phpstan

